FROM alpine:3.16.2

RUN   echo "**** install runtime packages ****" && \
    apk add --no-cache \
# curl \
# expat \
# ffmpeg \
# ffmpeg-libs \
# fftw \
# flac \
# gdbm \
# gst-plugins-good \
# gstreamer \
# jpeg \
# jq \
# lame \
# libffi \
# libpng \
# mpg123 \
# nano \
# openjpeg \
# py3-gobject3 \
# py3-pip \
# py3-pylast \
# python3 \
# sqlite-libs \
# tar \
# wget \
    mp3gain \
      mp3val \
    chromaprint \
    beets \
#  &&   python3 -m pip install --upgrade pip \
  && rm -rf \
    /root/.cache \
    /tmp/*
